### ISSUE TITLE
Deploy to IBM Cloud button is broken.

### ISSUE THREAD

**Issue by MarvinDivo** [IBM/guide-conveyor-simulator#8]
Hello.
Deploy to IBM Cloud button is broken.

Steps to recreate:
Press button 'Deploy to IBM Cloud'.

Expected: 
Deployment to IBM Cloud started

Actual:
Error message: Page not found.

**Comment by ljbennett62** [comment]
@MarvinDivo - the button works now - please give it a try now.

**Comment by MarvinDivo** [comment]
Thank you @ljbennett62. Now its works.
